# $OpenBSD$

COMMENT =	Mozilla's CA cert bundle in PEM format
DISTNAME =	Mozilla-CA-20200520
PKG_ARCH =	*
CATEGORIES =	www

# Mozilla Public License, v. 2.0
PERMIT_PACKAGE =	Yes

MODULES =		cpan

.include <bsd.port.mk>
