# $OpenBSD$

COMMENT =	create a minimal mirror of CPAN
DISTNAME =	CPAN-Mini-1.111016
PKG_ARCH =	*
CATEGORIES =	sysutils

# Perl
PERMIT_PACKAGE =	Yes

MODULES =	cpan

RUN_DEPENDS =		devel/p5-File-HomeDir>=0.57 \
			www/p5-libwww>=5 \
			www/p5-URI>=1

.include <bsd.port.mk>
