# $OpenBSD$

COMMENT =	Metabase transport for Test::Reporter
DISTNAME =	Test-Reporter-Transport-Metabase-1.999010
PKG_ARCH =	*
CATEGORIES =	devel

# Apache 2.0
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		converters/p5-JSON-MaybeXS \
			devel/p5-CPAN-Testers-Report>=1.999001 \
			devel/p5-Metabase-Client-Simple>=0.008 \
			devel/p5-Metabase-Fact>=0.016 \
			devel/p5-Test-Reporter>=1.57

.include <bsd.port.mk>
