#!/bin/sh
# doas perl -ani -E '$F[3] .= ",softdep,noatime" if $F[1] =~ m{/home|/minicpan|/tmp}; say "@F"' /etc/fstab

# TODO:
# * Install plenv "system-wide" instead of per-user

doas -n pkg_add git bash

# Ignore erros in the `doas` above, they have probably already run
set -e

set -x
while read src dst; do
    if [ -e ~/$dst/.git ]; then
        ( cd ~/$dst && git pull )
    else
        git clone $src ~/$dst
    fi
done <<EOL
https://github.com/tokuhirom/plenv.git        .plenv
https://github.com/tokuhirom/Perl-Build.git   .plenv/plugins/perl-build
https://github.com/miyagawa/plenv-contrib.git .plenv/plugins/plenv-contrib
EOL

# If we need plenv exec-all --match, we need instead:
#git clone https://github.com/afresh1/plenv-contrib.git ~/.plenv/plugins/plenv-contrib/
#( cd ~/.plenv/plugins/plenv-contrib && git checkout exec-match )

mkdir -p ~/.plenv/libexec ~/.plenv/plenv.d/exec

for f in \
    plenv/libexec/plenv-install-latest \
    plenv/plenv.d/exec/carton_path.bash \
; do
    ftp -o ~/.$f https://raw.githubusercontent.com/afresh1/dotfiles/blead/$f
    chmod +x ~/.$f
done

cat <<EOL >~/.plenv/extra-modules
CPAN

# Install toolchain modules
ExtUtils::CBuilder
Module::Build
Module::Build
Archive::Tar
YAML
YAML::XS
Test::Pod
Test::Pod::Coverage
Digest::SHA
version

# Install Task::CPAN::Reporter and CPAN::Reporter::Smoker

Task::CPAN::Reporter
CPAN::Reporter::Smoker

# Install some extra stuff
Module::Signature
Log::Log4perl
HTTP::Date
local::lib
LWP::Protocol::https
HTTP::Tiny
CPAN::SQLite
Term::Title
EOL

PATH="$HOME/.plenv/bin:$PATH"
eval "$(plenv init -)"

# To start, I only want to test semi-recent perls
plenv install-latest -o 5.24

# We only want a max of three threded perls
# so we trust the "full" list of non-threaded to be more complete
oldest=$( plenv versions --bare | grep -x '5\.[0-9][0-9]' | tail -3 | head -1 )
plenv install-latest -o $oldest -s -threaded -- -Dusethreaded

# Now we remove threaded versions that are older than we want
threaded=$( plenv versions --bare | grep -e '-threaded$' )
oldest=$( echo "$threaded" | tail -3 | head -1 )
set --
for v in $threaded; do
	[ "$v" = "$oldest" ] && break
	set -- "$@" "$( plenv prefix "$v" )"
done
[ "$*" ] && rm -rf "$@"

cat <<'EOL' >> ~/.profile
PATH="$HOME/.plenv/bin:$PATH"
eval "$(plenv init -)"
EOL
