# $OpenBSD$

COMMENT =	write a CHECKSUMS file for a directory as on CPAN
DISTNAME =	CPAN-Checksums-2.12
PKG_ARCH =	*
CATEGORIES =	devel

# Perl
PERMIT_PACKAGE =	Yes

MODULES =	cpan

RUN_DEPENDS =	archivers/p5-Compress-Bzip2 \
		devel/p5-Data-Compare \
		security/p5-Module-Signature

.include <bsd.port.mk>
