# $OpenBSD$

COMMENT =	CPAN Testers report object
DISTNAME =	CPAN-Testers-Report-1.999003
PKG_ARCH =	*
CATEGORIES =	devel

# Apache 2.0
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		devel/p5-Metabase-Fact>=0.016

.include <bsd.port.mk>
