# $OpenBSD$

COMMENT =	extract name and version from a distribution
DISTNAME =	CPAN-DistnameInfo-0.12
PKG_ARCH =	*
CATEGORIES =	devel

# Perl
PERMIT_PACKAGE =	Yes

MODULES =	cpan

.include <bsd.port.mk>
