# $OpenBSD$

COMMENT =	base class for Metabase Facts
DISTNAME =	Metabase-Fact-0.025
CPAN_AUTHOR =	DAGOLDEN
PKG_ARCH =	*
CATEGORIES =	devel

# Apache 2.0
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		converters/p5-JSON-MaybeXS \
			devel/p5-CPAN-DistnameInfo \
			devel/p5-Data-GUID \
			devel/p5-IO-Prompt-Tiny
TEST_DEPENDS =		devel/p5-Test-Fatal

.include <bsd.port.mk>
