# $OpenBSD$

COMMENT =	read and write a subset of YAML for CPAN Meta files
DISTNAME =	CPAN-Meta-YAML-0.018
PKG_ARCH =	*
CATEGORIES =	devel

FIX_EXTRACT_PERMISSIONS =	Yes

# Perl
PERMIT_PACKAGE =	Yes

MODULES =	cpan

.include <bsd.port.mk>
