# $OpenBSD$

COMMENT =	set autoflush from the command line
DISTNAME =	Devel-Autoflush-0.06
PKG_ARCH =	*
CATEGORIES =	devel

# Apache 2.0
PERMIT_PACKAGE =	Yes

MODULES =	cpan

TEST_DEPENDS =	devel/p5-IO-CaptureOutput>=1.08

.include <bsd.port.mk>
